// <auto-generated />
namespace DPTS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addSession1Session2Appoinment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSession1Session2Appoinment));
        
        string IMigrationMetadata.Id
        {
            get { return "201705180421307_addSession1Session2Appoinment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
